### ISSUE TITLE
Unused dependencies should be marked as warning not as error

### ISSUE THREAD

**Issue by Thomas-Bergmann** [IntershopCommunicationsAG/dependencyanalysis-gradle-plugin#3]
Unused dependencies will not have an impact to a production system. Therefore it should be a warning not an error.

**Comment by m-raab** [comment]
I will check the analysis, but runtime dependencies are not analyzed.

**Comment by Thomas-Bergmann** [comment]
The main problem with "unused dependencies" is following:
- I use the dependency in my production project
- I have to fix my project and now I don't need the dependency anymore (e.g. I use another framework)
- I can't remove the dependency, because this will break the API of my project and I have to release a new major version

**Comment by m-raab** [comment]
the concept was changed.
