### ISSUE TITLE
exclude 

### ISSUE THREAD

**Issue by Thomas-Bergmann** [IntershopCommunicationsAG/dependencyanalysis-gradle-plugin#5]
build.gradle

```
compile ('com.netflix.eureka:eureka-client-jersey2:1.4.6') {
  exclude group: 'javax.ws.rs', module: 'jsr311-api'
  exclude group: 'javax.servlet', module: 'servlet-api' // servlet api is now module 'javax.servlet-api'
  exclude group: 'org.glassfish.hk2.external'
}
```

In java file we use:

```
import com.netflix.appinfo.MyDataCenterInstanceConfig;
public class EurekaInstanceConfigImpl extends MyDataCenterInstanceConfig
```

The dependency analysis task fails, because of

`Not used   com.netflix.eureka:eureka-client-jersey2:1.4.6`

**Comment by m-raab** [comment]
com.netflix.appinfo.MyDataCenterInstanceConfig is not part of com.netflix.eureka:eureka-client-jersey2:1.4.6. This should be a runtime dependency and not a compile dependency.
