### ISSUE TITLE
Is it possible to fail the build only with duplicated classes detection?

### ISSUE THREAD

**Issue by persapiens** [IntershopCommunicationsAG/dependencyanalysis-gradle-plugin#6]
In my case, I am interested only when there are duplicated classes.

**Comment by m-raab** [comment]
I want start a rework of this plugin for Gradle 4. I will add this configuration to the plugin.

**Comment by persapiens** [comment]
Great @m-raab. 

The functionality I talk about is like what [duplicate-finder-maven-plugin](https://github.com/basepom/duplicate-finder-maven-plugin) provides.

**Comment by m-raab** [comment]
the behavior was changed.

**Comment by m-raab** [comment]
the behavior was changed.

**Comment by m-raab** [comment]
Please see the documentation of the new version.
